version: "3"
services:
  anu:
    # replace username/repo:tag with your name and image details
    image: kevinputera/get-started:part2
    ports:
      - "80:80"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports: 
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - "data:/home/docker/data"
    networks:
      - webnet
networks:
  webnet:
